tasks:
  - name: Setup Development Env
    openMode: tab-after
    init: |
      type -p curl >/dev/null || sudo apt install curl -y
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt update
      sudo apt install gh -y
      gp sync-done dev-setup
  - name: Install ODK Central
    openMode: tab-after
    init: |
      gp sync-done dev-setup
      bash install-central.sh
  - name: Start Services
    openMode: tab-after
    init: |
      gp sync-done dev-setup
      sed -i~ "/^FORM_MANAGER_URL=/s/=.*/=https\:\/\/3006-${GITPOD_WORKSPACE_URL:8}/" .env
      sed -i~ "/^MINIO_URL=/s/=.*/=https\:\/\/9000-${GITPOD_WORKSPACE_URL:8}/" .env
      docker-compose up -d
      gp sync-done setup
  - name: Setup React Wrapper
    openMode: tab-after
    init: |
      gp sync-await setup
      cd apps/wrapper
      nvm use 16
      pnpm install
      bash make-envs-for-react.sh
    command: |
      npm run start
      
ports:
  - port: 8065
    onOpen: ignore
    visibility: public
    description: Enketo Express

  - port: 3006
    onOpen: ignore
    visibility: public
    description: Form Manager

  - port: 3000 
    onOpen: ignore
    visibility: public
    description: React Wrapper

  - port: 8080
    onOpen: ignore
    visibility: public
    description: Hasura

  - port: 9011 
    onOpen: ignore
    visibility: public
    description: Fusion Auth

  - port: 8090 
    onOpen: ignore
    visibility: public
    description: ODK Central

  - port: 9001 
    onOpen: ignore
    visibility: public
    description: Minio UI
  
  - port: 9000 
    onOpen: ignore
    visibility: public
    description: Minio API