tasks:
  - name: Setup Enketo Express
    openMode: tab-after
    init: |
      bash install-node.sh
      nvm use 14
      cd packages/enketo-express && pnpm i && pnpm i -g grunt
      gp sync-done setup
    command: |
      grunt develop
  - name: Setup Form Manager
    openMode: tab-after
    init: |
      gp sync-await setup
      cd packages/form-manager
      nvm use 16
      pnpm install
    command: |
      npm run start:dev
  - name: Setup React Wrapper
    openMode: tab-after
    init: |
      gp sync-await setup
      cd apps/wrapper
      nvm use 16
      pnpm install
    command: |
      npm run start
      
ports:
  - port: 8065 # Enketo Express
    onOpen: ignore
    visibility: public
  - port: 3006 # Form Manager
    onOpen: ignore
    visibility: public
  - port: 3000 # React Wrapper
    onOpen: ignore
    visibility: public
  - port: 8080 # React Wrapper
    onOpen: ignore
    visibility: public