tasks:
  - name: Setup Development Env
    openMode: tab-after
    init: |
      sudo apt update
      sudo apt install gh
      gp sync-done dev-setup
  - name: Install ODK Central
  - name: Setup Enketo Express
    openMode: tab-after
    init: |
      gp sync-done dev-setup
      bash install-node.sh
      nvm use 14
      cd packages/enketo-express && pnpm i && pnpm i -g grunt
      bash update-config.sh
      gp sync-done setup
    command: |
      grunt develop
  - name: Setup Form Manager
    openMode: tab-after
    init: |
      gp sync-await setup
      cd packages/form-manager
      nvm use 16
      pnpm install
    command: |
      npm run start:dev
  - name: Setup React Wrapper
    openMode: tab-after
    init: |
      gp sync-await setup
      cd apps/wrapper
      nvm use 16
      pnpm install
      bash make-envs-for-react.sh
    command: |
      npm run start
      
ports:
  - port: 8065
    onOpen: ignore
    visibility: public
    description: Enketo Express

  - port: 3006
    onOpen: ignore
    visibility: public
    description: Form Manager

  - port: 3000 
    onOpen: ignore
    visibility: public
    description: React Wrapper

  - port: 8080
    onOpen: ignore
    visibility: public
    description: Hasura

  - port: 9011 
    onOpen: ignore
    visibility: public
    description: Fusion Auth

  - port: 8090 
    onOpen: ignore
    visibility: public
    description: ODK Central

  - port: 9001 
    onOpen: ignore
    visibility: public
    description: Minio UI
  
  - port: 9000 
    onOpen: ignore
    visibility: public
    description: Minio API