tasks:
  - name: Setup Enketo Express
    openMode: tab-after
    init: |
      bash install-node.sh
      bash make-envs-for-react.sh
      nvm use 14
      cd packages/enketo-express && pnpm i && pnpm i -g grunt
      gp sync-done setup
    command: |
      grunt develop
  - name: Setup Form Manager
    openMode: tab-after
    init: |
      gp sync-await setup
      cd packages/form-manager
      nvm use 16
      pnpm install
    command: |
      npm run start:dev
  - name: Setup React Wrapper
    openMode: tab-after
    init: |
      gp sync-await setup
      cd apps/wrapper
      nvm use 16
      pnpm install
    command: |
      npm run start
      
ports:
  - port: 8065
    onOpen: ignore
    visibility: public
    description: Enketo Express

  - port: 3006
    onOpen: ignore
    visibility: public
    description: Form Manager

  - port: 3000 
    onOpen: ignore
    visibility: public
    description: React Wrapper

  - port: 8080
    onOpen: ignore
    visibility: public
    description: Hasura

  - port: 9011 
    onOpen: ignore
    visibility: public
    description: Fusion Auth