tasks:
  - name: Install things
    init: bash ./install-node.sh
  - name: Setup Enketo Express
    openMode: tab-after
    init: |
      nvm use 14
      npm start-ee
  - name: Setup Form Manager
    openMode: tab-after
    init: |
      nvm use 14
      npm run start:dev
  - name: Setup Enketo Express
    openMode: tab-after
    init: |
      nvm use 14
      grunt develop
  - name: Setup React Wrapper
    openMode: tab-after
    init: |
      nvm use 16
      npm run start
      
      

ports:
  - port: 8065 # Enketo Express
    onOpen: ignore
    visibility: public
  - port: 3006 # Form Manager
    onOpen: ignore
    visibility: public
  - port: 3000 # React Wrapper
    onOpen: ignore
    visibility: public